# Generated by Django 2.1 on 2018-12-24 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.University')),
            ],
        ),
    ]
