# Generated by Django 2.1 on 2019-01-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_book_dist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Distributor'),
        ),
    ]
